// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginReq struct {
	Account              *string  `protobuf:"bytes,1,req,name=Account" json:"Account,omitempty"`
	Password             *string  `protobuf:"bytes,2,req,name=Password" json:"Password,omitempty"`
	Name                 *string  `protobuf:"bytes,3,req,name=Name" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *LoginReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type LoginRes struct {
	Player               *Player   `protobuf:"bytes,2,req,name=Player" json:"Player,omitempty"`
	OtherPlayers         []*Player `protobuf:"bytes,3,rep,name=OtherPlayers" json:"OtherPlayers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *LoginRes) GetOtherPlayers() []*Player {
	if m != nil {
		return m.OtherPlayers
	}
	return nil
}

type Player struct {
	TokenID              *string    `protobuf:"bytes,1,req,name=TokenID" json:"TokenID,omitempty"`
	Name                 *string    `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	X                    *float32   `protobuf:"fixed32,3,req,name=X" json:"X,omitempty"`
	Y                    *float32   `protobuf:"fixed32,4,req,name=Y" json:"Y,omitempty"`
	Missions             []*Mission `protobuf:"bytes,5,rep,name=Missions" json:"Missions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetTokenID() string {
	if m != nil && m.TokenID != nil {
		return *m.TokenID
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Player) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Player) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Player) GetMissions() []*Mission {
	if m != nil {
		return m.Missions
	}
	return nil
}

type Mission struct {
	Id                   *int32   `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	Status               *int32   `protobuf:"varint,2,req,name=Status" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mission) Reset()         { *m = Mission{} }
func (m *Mission) String() string { return proto.CompactTextString(m) }
func (*Mission) ProtoMessage()    {}
func (*Mission) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *Mission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mission.Unmarshal(m, b)
}
func (m *Mission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mission.Marshal(b, m, deterministic)
}
func (m *Mission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mission.Merge(m, src)
}
func (m *Mission) XXX_Size() int {
	return xxx_messageInfo_Mission.Size(m)
}
func (m *Mission) XXX_DiscardUnknown() {
	xxx_messageInfo_Mission.DiscardUnknown(m)
}

var xxx_messageInfo_Mission proto.InternalMessageInfo

func (m *Mission) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Mission) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "proto.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "proto.LoginRes")
	proto.RegisterType((*Player)(nil), "proto.player")
	proto.RegisterType((*Mission)(nil), "proto.mission")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8e, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0xba, 0x76, 0xf5, 0x6d, 0xee, 0xf0, 0x0e, 0x12, 0x3c, 0x8d, 0x82, 0x20, 0x1e,
	0x06, 0xf3, 0x3f, 0x10, 0xbc, 0x14, 0xfc, 0x31, 0xe2, 0x0e, 0xdb, 0xb1, 0xac, 0x41, 0x8b, 0x5b,
	0x33, 0xf3, 0x32, 0xc4, 0x8b, 0x7f, 0xbb, 0xf4, 0x25, 0x8d, 0x88, 0xa7, 0xe4, 0xf3, 0xfd, 0xbe,
	0xe4, 0x7d, 0x60, 0xb2, 0x37, 0xaf, 0x6d, 0xb7, 0x38, 0x5a, 0xe3, 0x0c, 0x66, 0x7c, 0x94, 0x6b,
	0x28, 0x1e, 0xfa, 0x54, 0xe9, 0x0f, 0x94, 0x30, 0xbe, 0xdb, 0xed, 0xcc, 0xa9, 0x73, 0x32, 0x99,
	0x8b, 0xeb, 0x33, 0x35, 0x20, 0x5e, 0x42, 0xb1, 0xaa, 0x89, 0x3e, 0x8d, 0x6d, 0xa4, 0xe0, 0x2a,
	0x32, 0x22, 0x8c, 0x9e, 0xea, 0x83, 0x96, 0x29, 0xe7, 0x7c, 0x2f, 0x9b, 0xf8, 0x2b, 0xe1, 0x15,
	0xe4, 0xab, 0x7d, 0xfd, 0xa5, 0x2d, 0xbf, 0x9c, 0xdc, 0x9e, 0x7b, 0x81, 0xc5, 0x91, 0x43, 0x15,
	0x4a, 0x5c, 0xc2, 0xf4, 0xd9, 0xbd, 0x69, 0xeb, 0x91, 0x64, 0x3a, 0x4f, 0xff, 0x0f, 0xff, 0x19,
	0x29, 0xbf, 0x21, 0xf7, 0x79, 0x6f, 0xbe, 0x36, 0xef, 0xba, 0xab, 0xee, 0x07, 0xf3, 0x80, 0xd1,
	0x4e, 0xfc, 0xda, 0xe1, 0x14, 0x92, 0x0d, 0xeb, 0x0a, 0x95, 0x6c, 0x7a, 0xda, 0xca, 0x91, 0xa7,
	0x2d, 0xde, 0x40, 0xf1, 0xd8, 0x12, 0xb5, 0xa6, 0x23, 0x99, 0xb1, 0xc2, 0x2c, 0x28, 0x1c, 0x7c,
	0xac, 0x62, 0x5f, 0x2e, 0x61, 0x1c, 0x42, 0x9c, 0x81, 0xa8, 0x1a, 0xde, 0x9d, 0x29, 0x51, 0x35,
	0x78, 0x01, 0xf9, 0x8b, 0xab, 0xdd, 0x89, 0x78, 0x71, 0xa6, 0x02, 0xfd, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x39, 0x3f, 0x26, 0x33, 0x83, 0x01, 0x00, 0x00,
}
