// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mission.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MissionReq struct {
	Id                   *int32   `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	Account              *string  `protobuf:"bytes,2,req,name=Account" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MissionReq) Reset()         { *m = MissionReq{} }
func (m *MissionReq) String() string { return proto.CompactTextString(m) }
func (*MissionReq) ProtoMessage()    {}
func (*MissionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfcd1ec69bb1f75, []int{0}
}

func (m *MissionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MissionReq.Unmarshal(m, b)
}
func (m *MissionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MissionReq.Marshal(b, m, deterministic)
}
func (m *MissionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MissionReq.Merge(m, src)
}
func (m *MissionReq) XXX_Size() int {
	return xxx_messageInfo_MissionReq.Size(m)
}
func (m *MissionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MissionReq.DiscardUnknown(m)
}

var xxx_messageInfo_MissionReq proto.InternalMessageInfo

func (m *MissionReq) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MissionReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

type MissionRes struct {
	Id                   *int32   `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	Status               *int32   `protobuf:"varint,2,req,name=Status" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MissionRes) Reset()         { *m = MissionRes{} }
func (m *MissionRes) String() string { return proto.CompactTextString(m) }
func (*MissionRes) ProtoMessage()    {}
func (*MissionRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfcd1ec69bb1f75, []int{1}
}

func (m *MissionRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MissionRes.Unmarshal(m, b)
}
func (m *MissionRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MissionRes.Marshal(b, m, deterministic)
}
func (m *MissionRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MissionRes.Merge(m, src)
}
func (m *MissionRes) XXX_Size() int {
	return xxx_messageInfo_MissionRes.Size(m)
}
func (m *MissionRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MissionRes.DiscardUnknown(m)
}

var xxx_messageInfo_MissionRes proto.InternalMessageInfo

func (m *MissionRes) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MissionRes) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*MissionReq)(nil), "proto.MissionReq")
	proto.RegisterType((*MissionRes)(nil), "proto.MissionRes")
}

func init() { proto.RegisterFile("mission.proto", fileDescriptor_3cfcd1ec69bb1f75) }

var fileDescriptor_3cfcd1ec69bb1f75 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xcd, 0x2c, 0x2e,
	0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x66, 0x5c,
	0x5c, 0xbe, 0x10, 0xf1, 0xa0, 0xd4, 0x42, 0x21, 0x3e, 0x2e, 0x26, 0xcf, 0x14, 0x09, 0x46, 0x05,
	0x26, 0x0d, 0xd6, 0x20, 0x26, 0xcf, 0x14, 0x21, 0x09, 0x2e, 0x76, 0xc7, 0xe4, 0xe4, 0xfc, 0xd2,
	0xbc, 0x12, 0x09, 0x26, 0x05, 0x26, 0x0d, 0xce, 0x20, 0x18, 0x57, 0xc9, 0x04, 0x49, 0x5f, 0x31,
	0x86, 0x3e, 0x31, 0x2e, 0xb6, 0xe0, 0x92, 0xc4, 0x92, 0xd2, 0x62, 0xb0, 0x36, 0xd6, 0x20, 0x28,
	0x0f, 0x10, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x39, 0x10, 0xa5, 0x84, 0x00, 0x00, 0x00,
}
