version: '3'
services: 
    arpg:
        build: .
        ports:
            - "22:22"
            - "8000:8000"
        privileged: true
        volumes: 
            - .:/project
        links: 
            - db
            - redis
        tty: true
    db:
        image: mariadb
        restart: always
        ports:
            - "3308:3306"
        environment: 
            MYSQL_ROOT_PASSWORD : 1234
        volumes:
            - ./sqls:/docker-entrypoint-initdb.d
    redis:
        image: redis
        ports:
            - "6379:6379"